[package]
name = "dat-garscan-desktop"
version = "0.1.0"
description = "Dat-Gar Scan - Lector de mangas para escritorio"
authors = ["Dat-Gar Scanlation"]
edition = "2021"

[lib]
name = "dat_garscan_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
tauri-plugin-http = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
